### ISSUE TITLE
Keys are visible

### ISSUE THREAD

**Issue by Bigghead** [michal9909/book-trading-club#1]
Hey dude, I saw your portfolio and checked out your projects' github. You have all the keys visible to everybody. Everybody has full access to your DB through RoboMongo

**Comment by michal9909** [comment]
@Bigghead Hah yeah thanks for letting me know. I will fix this tomorrow.

**Comment by michal9909** [comment]
Keys have been replaced with environment variables although still are shown in the commit history. Will not bother with that since there is no sensitive data. Although I will pay more attention in future projects.
